import type { Metadata } from "next";
import { Inter } from 'next/font/google'
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "@/providers/Providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={inter.className} data-new-gr-c-s-check-loaded="14.1228.0"
        data-gr-ext-installed="">
        <Providers>
          <Toaster
            position="top-right"
            reverseOrder={false}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
